### ISSUE TITLE
DockerBaseTag interval update is 64 years

### ISSUE THREAD

**Issue by nfode** [StuPro-TOSCAna/TOSCAna#345] opened 2017-12-11 11:43 UTC
Starting the server I get the following log:
```
2017-12-11T12:39:28,530 [main] DEBUG o.o.t.p.k.d.mapper.BaseImageMapper   - Not updating docker base tags: Using local data (next persist: 2081-04-25T04:51:25.692Z)
```

The next persist date seems to be wrong, since the `application.yml` says the update interval is 24h.

**Comment by c-mueller** [comment] 2017-12-12 00:02
Did you clear your working directory?

If i run it (Let the Mapper download the data) and then relaunch it i get this:
```
2017-12-12T01:00:11,156 [main] DEBUG o.o.t.p.k.d.mapper.BaseImageMapper   - Not updating docker base tags: Using local data (next persist: 2017-12-12T23:59:49.839Z) 
```

**Comment by hnicke** [comment] 2018-01-16 18:42
@nfode did c-muellers proposal solve your issue?

**Comment by c-mueller** [comment] 2018-01-31 19:48
I think this is no longer a issue. At least i was never able to reproduce the problem.

Going to close this because of that

**Closed by c-mueller** 2018-01-31 19:48 UTC
Labels: bug, not-reproducible, plugin/kubernetes
